<?php
return array (
  'truename' => 
  array (
    'fieldid' => '1169',
    'modelid' => '42',
    'siteid' => '0',
    'field' => 'truename',
    'name' => '真实姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'district' => 
  array (
    'fieldid' => '1168',
    'modelid' => '42',
    'siteid' => '0',
    'field' => 'district',
    'name' => '工作区域',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 'array (
  \'linkageid\' => \'4000\',
  \'showtype\' => \'2\',
  \'space\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '4000',
    'showtype' => '2',
    'space' => '',
  ),
  'company' => 
  array (
    'fieldid' => '1166',
    'modelid' => '42',
    'siteid' => '0',
    'field' => 'company',
    'name' => '所属公司',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<input type=\\\'hidden\\\' name=\\\'info[company]\\\' id=\\\'company\\\' value=\\\'{FIELD_VALUE}\\\' style=\\\'50\\\' >
<input type=\\\'hidden\\\' name=\\\'info[companyname]\\\' id=\\\'companyname\\\' style=\\\'50\\\' >
<input class=\\\'input-text\\\' id=\\\'relation_lp_text\\\' readonly/>
<input type=\\\'button\\\' value="选择公司" onclick="omnipotent(\\\'selectid\\\',\\\'?s=member/index/public_member_companylist/type/company\\\',\\\'添加所属公司\\\',1,500,470)" class="button">
<span class="edit_content">
<input type=\\\'button\\\' value="独立经纪人" onclick="remove_company()" class="button">
</span>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<input type=\'hidden\' name=\'info[company]\' id=\'company\' value=\'{FIELD_VALUE}\' style=\'50\' >
<input type=\'hidden\' name=\'info[companyname]\' id=\'companyname\' style=\'50\' >
<input class=\'input-text\' id=\'relation_lp_text\' readonly/>
<input type=\'button\' value="选择公司" onclick="omnipotent(\'selectid\',\'?s=member/index/public_member_companylist/type/company\',\'添加所属公司\',1,500,470)" class="button">
<span class="edit_content">
<input type=\'button\' value="独立经纪人" onclick="remove_company()" class="button">
</span>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'tel' => 
  array (
    'fieldid' => '1165',
    'modelid' => '42',
    'siteid' => '0',
    'field' => 'tel',
    'name' => '联系电话',
    'tips' => '',
    'css' => '',
    'minlength' => '11',
    'maxlength' => '11',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '请输入正确的手机号',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>