<?php
return array (
  'catid' => 
  array (
    'fieldid' => '993',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '6',
    'pattern' => '/^[0-9]{1,6}$/',
    'errortips' => '请选择栏目',
    'formtype' => 'catid',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'typeid' => 
  array (
    'fieldid' => '994',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'typeid',
    'name' => '类别',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'typeid',
    'setting' => 'array (
  \'minnumber\' => \'\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '',
    'defaultvalue' => '',
  ),
  'title' => 
  array (
    'fieldid' => '995',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'title',
    'name' => '标题',
    'tips' => '',
    'css' => 'inputtitle',
    'minlength' => '1',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => 'array (
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'belong' => 
  array (
    'fieldid' => '1030',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'belong',
    'name' => '产权',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'私产|1
公产|2
商品房|3
期房|4
经济适用房|5
使用权房|6
房改房|7\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '私产|1
公产|2
商品房|3
期房|4
经济适用房|5
使用权房|6
房改房|7',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'type' => 
  array (
    'fieldid' => '1028',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'type',
    'name' => '房屋类型',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'住宅|1
花园洋房|2
酒店式公寓|3
商住两用|4
综合体|5
别墅|6
写字楼|7
商铺|8
公寓|9
经济适用房|10\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '住宅|1
花园洋房|2
酒店式公寓|3
商住两用|4
综合体|5
别墅|6
写字楼|7
商铺|8
公寓|9
经济适用房|10',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '0',
  ),
  'huxingyang' => 
  array (
    'fieldid' => '1029',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'huxingyang',
    'name' => '阳',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'1|1
2|2
3|3
4|4
5|5\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'options' => '1|1
2|2
3|3
4|4
5|5',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'huxing' => 
  array (
    'fieldid' => '1022',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'huxing',
    'name' => '户型',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'{huxingshi} 室 {huxingting} 厅 {huxingwei} 卫 {huxingyang} 阳　　第 {floor}  层，总 {zonglouceng} 层\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '{huxingshi} 室 {huxingting} 厅 {huxingwei} 卫 {huxingyang} 阳　　第 {floor}  层，总 {zonglouceng} 层',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'huxingwei' => 
  array (
    'fieldid' => '1019',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'huxingwei',
    'name' => '卫',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'1|1
2|2
3|3
4|4
5|5\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'options' => '1|1
2|2
3|3
4|4
5|5',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'huxingting' => 
  array (
    'fieldid' => '1021',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'huxingting',
    'name' => '厅',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'1|1
2|2
3|3
4|4
5|5\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'options' => '1|1
2|2
3|3
4|4
5|5',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'huxingshi' => 
  array (
    'fieldid' => '1016',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'huxingshi',
    'name' => '室',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'1|1
2|2
3|3
4|4
5|5\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'options' => '1|1
2|2
3|3
4|4
5|5',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'floor' => 
  array (
    'fieldid' => '1017',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'floor',
    'name' => '楼层',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'2\',
  \'defaultvalue\' => \'1\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '2',
    'defaultvalue' => '1',
    'ispassword' => '0',
  ),
  'zonglouceng' => 
  array (
    'fieldid' => '1018',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'zonglouceng',
    'name' => '总楼层',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'2\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '2',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'house_status' => 
  array (
    'fieldid' => '1135',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_status',
    'name' => '房源属性',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'出售|1
下架|2
已成交|4\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'smallint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '6',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '出售|1
下架|2
已成交|4',
    'boxtype' => 'radio',
    'fieldtype' => 'smallint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
    'filtertype' => '1',
  ),
  'fix' => 
  array (
    'fieldid' => '1014',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'fix',
    'name' => '装修',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'毛坯|1
精装|2
中等装修|3
简装|4
豪华装修|5
原房|6\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '7',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '毛坯|1
精装|2
中等装修|3
简装|4
豪华装修|5
原房|6',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
    'filtertype' => '0',
  ),
  'region' => 
  array (
    'fieldid' => '1137',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'region',
    'name' => '区域',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 'array (
  \'linkageid\' => \'3360\',
  \'showtype\' => \'2\',
  \'space\' => \'\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '8',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '3360',
    'showtype' => '2',
    'space' => '',
    'filtertype' => '1',
  ),
  'flag' => 
  array (
    'fieldid' => '1160',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'flag',
    'name' => '标记',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'新推|1
急售|2
推荐|3
置顶|4
多图|5\',
  \'boxtype\' => \'checkbox\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '9',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '新推|1
急售|2
推荐|3
置顶|4
多图|5',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
    'filtertype' => '1',
  ),
  'recommend' => 
  array (
    'fieldid' => '1188',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'recommend',
    'name' => '店铺推荐',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'是|1
否|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '9',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '是|1
否|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'price' => 
  array (
    'fieldid' => '1027',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'price',
    'name' => '总价',
    'tips' => '万',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'20\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '20',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'house_toward' => 
  array (
    'fieldid' => '1025',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_toward',
    'name' => '朝向',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'东|1
南|2
西|3
北|4
东南|5
东北|6
西南|7
西北|8
南北|9
东西|10\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '东|1
南|2
西|3
北|4
东南|5
东北|6
西南|7
西北|8
南北|9
东西|10',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
    'filtertype' => '0',
  ),
  'wyf' => 
  array (
    'fieldid' => '1024',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'wyf',
    'name' => '物业管理费',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'20\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '20',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'tel' => 
  array (
    'fieldid' => '1023',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'tel',
    'name' => '电话',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'20\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '20',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'total_area' => 
  array (
    'fieldid' => '1015',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'total_area',
    'name' => '面积',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'20\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '20',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'description' => 
  array (
    'fieldid' => '997',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'description',
    'name' => '摘要',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'98\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '98',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'range' => 
  array (
    'fieldid' => '1145',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'range',
    'name' => '价格区间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'30万以下|1
30-40万|2
40-50万|3
50-60万|4
60-80万|5
80-100万|6
100-150万|7
150-200万|8\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '30万以下|1
30-40万|2
40-50万|3
50-60万|4
60-80万|5
80-100万|6
100-150万|7
150-200万|8',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'area_range' => 
  array (
    'fieldid' => '1146',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'area_range',
    'name' => '面积区间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'70平米以下|1
70-90平米|3
90-120平米|4
120-150平米|5
150-200平米|6
200-300平米|7
300平米以上|8\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '70平米以下|1
70-90平米|3
90-120平米|4
120-150平米|5
150-200平米|6
200-300平米|7
300平米以上|8',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
  'mprice' => 
  array (
    'fieldid' => '1147',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'mprice',
    'name' => '单价',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => 'array (
  \'minnumber\' => \'1\',
  \'maxnumber\' => \'\',
  \'decimaldigits\' => \'0\',
  \'defaultvalue\' => \'\',
  \'rangetype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '1',
    'maxnumber' => '',
    'decimaldigits' => '0',
    'defaultvalue' => '',
    'rangetype' => '0',
  ),
  'house_pic' => 
  array (
    'fieldid' => '1026',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_pic',
    'name' => '户型图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images',
    'setting' => 'array (
  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',
  \'isselectimage\' => \'0\',
  \'upload_number\' => \'5\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'isselectimage' => '0',
    'upload_number' => '5',
  ),
  'house_age' => 
  array (
    'fieldid' => '1020',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_age',
    'name' => '建筑年代',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => 'array (
  \'minnumber\' => \'0\',
  \'maxnumber\' => \'\',
  \'decimaldigits\' => \'0\',
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
  \'rangetype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '0',
    'maxnumber' => '',
    'decimaldigits' => '0',
    'size' => '',
    'defaultvalue' => '',
    'rangetype' => '0',
  ),
  'house_room' => 
  array (
    'fieldid' => '1143',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_room',
    'name' => '室内图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images',
    'setting' => 'array (
  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',
  \'isselectimage\' => \'0\',
  \'upload_number\' => \'5\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'isselectimage' => '0',
    'upload_number' => '5',
  ),
  'house_outdoor' => 
  array (
    'fieldid' => '1144',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_outdoor',
    'name' => '室外图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images',
    'setting' => 'array (
  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',
  \'isselectimage\' => \'0\',
  \'upload_number\' => \'5\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'isselectimage' => '0',
    'upload_number' => '5',
  ),
  'communityname' => 
  array (
    'fieldid' => '1158',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'communityname',
    'name' => '小区名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'refresh' => 
  array (
    'fieldid' => '1185',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'refresh',
    'name' => '刷新次数',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => 'array (
  \'minnumber\' => \'0\',
  \'maxnumber\' => \'\',
  \'decimaldigits\' => \'0\',
  \'defaultvalue\' => \'2\',
  \'rangetype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '0',
    'maxnumber' => '',
    'decimaldigits' => '0',
    'defaultvalue' => '2',
    'rangetype' => '0',
  ),
  'house_downtime' => 
  array (
    'fieldid' => '1186',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'house_downtime',
    'name' => '下架时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'updatetime' => 
  array (
    'fieldid' => '998',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '12',
    'disabled' => '0',
    'isomnipotent' => '0',
    'dateformat' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '1',
    'defaultvalue' => '',
  ),
  'assort' => 
  array (
    'fieldid' => '1140',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'assort',
    'name' => '配套设施',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'有线电视|18
双人床|17
家电|16
灶具|15
小房|14
家具|12
电话|10
宽带|9
天然气|2
煤气|1
暖气|3
电梯|4
车位|5
储藏室/地下室|6
防盗门|7
空调|8
阳台封闭|11
热水|13\',
  \'boxtype\' => \'checkbox\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '12',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '有线电视|18
双人床|17
家电|16
灶具|15
小房|14
家具|12
电话|10
宽带|9
天然气|2
煤气|1
暖气|3
电梯|4
车位|5
储藏室/地下室|6
防盗门|7
空调|8
阳台封闭|11
热水|13',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
    'filtertype' => '1',
  ),
  'content' => 
  array (
    'fieldid' => '999',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'content',
    'name' => '内容',
    'tips' => '<div class="content_attr"><label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1" checked>是否获取内容第</label><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片
</div>',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '999999',
    'pattern' => '',
    'errortips' => '内容不能为空',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'1\',
  \'replacenum\' => \'2\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '13',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '1',
    'replacenum' => '2',
    'link_mode' => '0',
    'enablesaveimage' => '1',
  ),
  'thumb' => 
  array (
    'fieldid' => '1000',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'1\',
  \'upload_maxsize\' => \'1024\',
  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',
  \'watermark\' => \'0\',
  \'isselectimage\' => \'1\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '14',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '1024',
    'upload_allowext' => 'jpg|jpeg|gif|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'relation' => 
  array (
    'fieldid' => '1001',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'relation',
    'name' => '所属小区',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<input type=\\\'hidden\\\' name=\\\'info[relation]\\\' id=\\\'relation\\\' value=\\\'{FIELD_VALUE}\\\' style=\\\'50\\\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\\\'button\\\' value="添加相关" onclick="omnipotent(\\\'selectid\\\',\\\'?s=content/content/public_relationlist&modelid=40\\\',\\\'添加相关小区\\\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\\\'button\\\' value="显示已有" onclick="show_relation2(40,{MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '15',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<input type=\'hidden\' name=\'info[relation]\' id=\'relation\' value=\'{FIELD_VALUE}\' style=\'50\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\'button\' value="添加相关" onclick="omnipotent(\'selectid\',\'?s=content/content/public_relationlist&modelid=40\',\'添加相关小区\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\'button\' value="显示已有" onclick="show_relation2(40,{MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'inputtime' => 
  array (
    'fieldid' => '1003',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '17',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'posids' => 
  array (
    'fieldid' => '1004',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'posids',
    'name' => '推荐位',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'posid',
    'setting' => 'array (
  \'cols\' => \'4\',
  \'width\' => \'125\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '18',
    'disabled' => '0',
    'isomnipotent' => '0',
    'cols' => '4',
    'width' => '125',
  ),
  'groupids_view' => 
  array (
    'fieldid' => '1005',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'groupids_view',
    'name' => '阅读权限',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'groupid',
    'setting' => 'array (
  \'groupids\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '19',
    'disabled' => '0',
    'isomnipotent' => '0',
    'groupids' => '',
  ),
  'remarks' => 
  array (
    'fieldid' => '1187',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'remarks',
    'name' => '备注',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '20',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'encode' => 
  array (
    'fieldid' => '1141',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'encode',
    'name' => '认证码',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '6',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '22',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'houseno' => 
  array (
    'fieldid' => '1142',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'houseno',
    'name' => '房源编号',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '22',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'url' => 
  array (
    'fieldid' => '1006',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '50',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'listorder' => 
  array (
    'fieldid' => '1007',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '6',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => 'array (
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '51',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'template' => 
  array (
    'fieldid' => '1008',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '30',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '53',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
  'allow_comment' => 
  array (
    'fieldid' => '1009',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'allow_comment',
    'name' => '允许评论',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'允许评论|1
不允许评论|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'88\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '54',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '允许评论|1
不允许评论|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '88',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'status' => 
  array (
    'fieldid' => '1010',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '2',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '55',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'username' => 
  array (
    'fieldid' => '1012',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '98',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'uid' => 
  array (
    'fieldid' => '1139',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'uid',
    'name' => 'uid',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '99',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'isbroker' => 
  array (
    'fieldid' => '1189',
    'modelid' => '39',
    'siteid' => '1',
    'field' => 'isbroker',
    'name' => '经纪人房源',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'是|1
否|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '99',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '是|1
否|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '1',
    'filtertype' => '1',
  ),
);
?>