<?php
return array (
  'title' => '区域',
  'style' => '1',
  'setting' => 
  array (
    'level' => '2',
  ),
  'siteid' => '1',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '环翠区',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3376,3417,3374,3378,3414,3385,3382,3375,3415',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '122.11734401987|37.510618015036',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '菊花顶中心区',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '皇冠九龙湾',
      'style' => '0',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '寨子万家疃',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '荣成市区',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '文登市区',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '乳山市区',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '经区',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3383,3384,3389,3416,3387,3388',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '122.14888143445|37.430716583374',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '南海',
      'style' => '0',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3368',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '利群哈工大',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '车站蒿泊',
      'style' => '0',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '成山',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '银滩',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '老车站海港',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3417',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '竹岛大润发',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '3',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '卧龙山',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '3',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '新港',
      'style' => '0',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '3',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '石岛',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '3',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '高区',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3386,3379,3377,3373,3380',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '122.05891478007|37.523697580224',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '田村后峰西',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '望岛戚家庄',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '港西',
      'style' => '0',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '长峰',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3416',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '荣成市',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3365,3394,3392,3393,3390,3381',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '122.48667144775|37.165241241455',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '国际海水浴场',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '其他',
      'style' => '0',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '新都凤林',
      'style' => '0',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '孙家疃',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '文登市',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3366,3395,3368',
      'keyid' => '3360',
      'listorder' => '6',
      'description' => '122.05812835693|37.193912506104',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '半月湾',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '6',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '天东曲阜',
      'style' => '0',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '6',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '乳山市',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3367,3396,3397',
      'keyid' => '3360',
      'listorder' => '7',
      'description' => '121.53976440429|36.919815063476',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '温泉江家寨',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '7',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '工业新区',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3364',
      'keyid' => '3360',
      'listorder' => '8',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '张村',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '8',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '1',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '羊亭',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3360',
      'listorder' => '9',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
  ),
);
?>