<?php return array (
  'name' => 'house5',
  'author' => 'HOUSE5 TEAM',
  'dirname' => 'default',
  'homepage' => 'http://www.house5.net/',
  'version' => '1.0',
  'disable' => 0,
  'file_explan' => 
  array (
    'templates|default|content' => 
    array (
      'category.html' => '文章频道页',
      'category_download.html' => '下载频道页',
      'category_home.html' => '家居首页',
      'category_house.html' => '新房频道页',
      'category_kanfang.html' => '看房团首页',
      'category_news.html' => '资讯首页',
      'category_picture.html' => '图片频道页',
      'category_shop.html' => '商业地产首页',
      'category_trip.html' => '旅游地产首页',
      'download.html' => '下载连接页',
      'esf_post.html' => '',
      'esf_show.html' => '',
      'footer.html' => '底部',
      'head_house.html' => '房产顶部',
      'header_page.html' => '单网页头部',
      'header_rss.html' => 'RSS订阅中心头部',
      'house_index.html' => '新房首页',
      'index.html' => '网站首页',
      'list.html' => '列表页',
      'list_baojia.html' => '楼盘报价单',
      'list_download.html' => '下载列表页',
      'list_esf.html' => '二手房列表页',
      'list_fangyuan.html' => '房源列表页',
      'list_head_house.html' => '楼盘超市页顶部',
      'list_house.html' => '房产列表页',
      'list_house_mobile.html' => '手机端楼盘超市页',
      'list_huxing.html' => '户型列表',
      'list_index_mobile.html' => '手机端问房网首页',
      'list_kanfangtuan.html' => '看房团首页',
      'list_mobile.html' => '手机端资讯首页',
      'list_news.html' => '即时资讯页',
      'list_news_wx.html' => '',
      'list_page_mobile.html' => '手机端新闻列表分页',
      'list_picnews.html' => '图片资讯页',
      'list_picture.html' => '图片列表页',
      'list_qqqun.html' => '业主qq群',
      'list_search.html' => '搜索首页',
      'list_search_mobile.html' => '手机端新闻搜索',
      'list_shop.html' => '商业地产首页',
      'list_trip.html' => '旅游地产首页',
      'list_wenfang.html' => '问房列表页',
      'list_xiangce.html' => '相册列表',
      'list_ybj.html' => '样板间列表',
      'list_zimu.html' => '字母索引列表',
      'lp_duibi.html' => '楼盘对比页',
      'message.html' => '消息提示页',
      'page.html' => '单网页',
      'rss.html' => 'RSS页',
      'search.html' => '搜索',
      'show.html' => '文章内容页',
      'show_company.html' => '公司介绍页',
      'show_data.html' => '成交数据内容页',
      'show_download.html' => '下载内容页',
      'show_fangyuan.html' => '房源内容页',
      'show_house.html' => '房产内容页',
      'show_house_dianping.html' => '楼盘点评',
      'show_house_dongtai.html' => '房产销售动态页',
      'show_house_huxing.html' => '房产户型页',
      'show_house_huxing_mobile.html' => '手机端楼盘户型图',
      'show_house_jiage.html' => '房产价格明细页',
      'show_house_mobile.html' => '手机端楼盘详情',
      'show_house_peitao.html' => '房产地图配套页',
      'show_house_right.html' => '房产内页右边调用',
      'show_house_showphoto.html' => '房产相册浏览页',
      'show_house_showphoto_mobile.html' => '手机端楼盘相册',
      'show_house_showpic.html' => '房产户型浏览页',
      'show_house_showpic_mobile.html' => '手机端楼盘户型浏览',
      'show_house_top1.html' => '楼盘详情顶部导航',
      'show_house_top2.html' => '楼盘详情底部导航',
      'show_house_wenfang.html' => '房产问房列表页',
      'show_house_xiangce.html' => '房产图片相册页',
      'show_house_xiangce_mobile.html' => '手机端楼盘相册',
      'show_house_xinxi.html' => '房产详细信息页',
      'show_house_zixun.html' => '房产相关资讯页',
      'show_kanfangtuan.html' => '看房团内容页',
      'show_mobile.html' => '手机端新闻内容页',
      'show_news_wx.html' => '',
      'show_page_mobile.html' => '手机端新闻内容分页',
      'show_picture.html' => '图片内容页',
      'show_video.html' => '',
      'tag.html' => 'tag',
    ),
    'templates|default|' => 
    array (
      'announce' => '公告',
      'comment' => '评论',
      'content' => '内容模型',
      'formguide' => '表单向导',
      'link' => '友情链接',
      'member' => '会员中心',
      'message' => '短消息',
      'mood' => '新闻心情',
      'pay' => '支付',
      'poster' => '广告',
      'search' => '搜索',
      'special' => '专题',
      'vote' => '投票',
      'wap' => '手机门户',
      'yp' => '黄页模板',
    ),
    'templates|default|vote' => 
    array (
      'index.html' => '',
      'list_new.html' => '列表页',
      'show.html' => '展示页',
      'submit.html' => '投票页',
      'vote_result.html' => '投票结果页',
      'vote_tp.html' => '单独显示页',
      'vote_tp_2.html' => '新闻页投票模版',
      'vote_tp_3.html' => '首页投票模版',
    ),
    'templates|default|link' => 
    array (
      'index.html' => '',
      'list_type.html' => '分类页',
      'register.html' => '申请页',
    ),
    'templates|default|special' => 
    array (
      'api_picture.html' => '组图',
      'comment.html' => '专题首页评论页',
      'header.html' => '专题头部',
      'index.html' => '专题首页',
      'list.html' => '分类页',
      'show.html' => '内容页',
      'special_list.html' => '专题列表',
    ),
    'templates|default|poster' => 
    array (
      'banner.html' => '矩形横幅',
      'couplet.html' => '对联广告',
      'fixure.html' => '固定位置',
      'float.html' => '漂浮移动',
      'imagechange.html' => '图片轮换广告',
      'imagelist.html' => '图片列表广告',
      'test.html' => '',
      'text.html' => '文字广告',
    ),
    'templates|default|pay' => 
    array (
      'deposit.html' => '支付页模板',
      'pay_list.html' => '支付记录页模板',
      'payment_cofirm.html' => '支付确认页模板',
      'spend_list.html' => '消费记录页模板',
    ),
    'templates|default|message' => 
    array (
      'group.html' => '系统消息',
      'inbox.html' => '收件箱',
      'outbox.html' => '发件箱',
      'read.html' => '短消息查看',
      'read_group.html' => '系统消息查看',
      'read_only.html' => '已经发消息',
      'send.html' => '写消息',
    ),
    'templates|default|member' => 
    array (
      'account_manage.html' => '会员管理',
      'account_manage_avatar.html' => '头像管理',
      'account_manage_info.html' => '会员信息管理',
      'account_manage_left.html' => '会员信息管理左侧菜单',
      'account_manage_password.html' => '修改密码',
      'account_manage_upgrade.html' => '会员升级',
      'change_credit.html' => '兑换积分',
      'connect_sina.html' => '新浪账号登陆',
      'content_publish.html' => '投稿页面',
      'content_publish_select_model.html' => '投稿模型选择',
      'content_published.html' => '已投稿管理',
      'favorite_list.html' => '收藏列表',
      'footer.html' => '页尾',
      'forget_password.html' => '密码找回页面',
      'header.html' => '页头',
      'index.html' => '首页',
      'left.html' => '左侧菜单',
      'login.html' => '登陆页面',
      'mini.html' => '头部登录条',
      'protocol.html' => '注册协议',
      'register.html' => '注册页面',
    ),
    'templates|default|phpsso' => 
    array (
      'index.html' => '首页',
    ),
    'templates|default|search' => 
    array (
      'footer.html' => '页尾',
      'header.html' => '页头',
      'index.html' => '首页',
      'list.html' => '列表页',
    ),
    'templates|default|formguide' => 
    array (
      'index.html' => '表单列表页模板',
      'show.html' => '表单详情页模板',
      'show_js.html' => '表单js调用模板',
    ),
    'templates|default|mood' => 
    array (
      'index.html' => '新闻心情',
    ),
    'templates|default|yp' => 
    array (
      'com_default' => '企业默认模板',
      'index.html' => '黄页首页模板',
      'list.html' => '列表页模板',
      'list_news.html' => '新闻列表页模板',
      'model.html' => '模型首页模板',
      'model_news.html' => '',
      'show.html' => '',
      'show_news.html' => '',
    ),
    'templates|default|yp|com_default' => 
    array (
      'index.html' => '公司首页模板',
      'style' => '样式文件夹',
    ),
    'templates|default|comment' => 
    array (
      'show_list.html' => '内容页评论列表',
      'list.html' => '评论列表',
    ),
    'templates|default|reviews' => 
    array (
      'show_list.html' => '内容页点评列表',
      'list.html' => '点评列表',
      'show_milist.html' => '内容页点评列表2',
    ),
  ),
);?>