<?php
return array (
  10 => 
  array (
    'modelid' => '10',
    'siteid' => '1',
    'name' => '普通会员',
    'description' => '普通会员',
    'tablename' => 'member_detail',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  35 => 
  array (
    'modelid' => '35',
    'siteid' => '1',
    'name' => '代理商',
    'description' => '楼盘代理商、分销商',
    'tablename' => 'member_daili',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '1',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  36 => 
  array (
    'modelid' => '36',
    'siteid' => '1',
    'name' => '开发商',
    'description' => '楼盘开发商',
    'tablename' => 'member_kfs',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  42 => 
  array (
    'modelid' => '42',
    'siteid' => '1',
    'name' => '经纪人',
    'description' => '经纪人',
    'tablename' => 'member_broker',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '2',
    'type' => '2',
  ),
  43 => 
  array (
    'modelid' => '43',
    'siteid' => '1',
    'name' => '中介公司',
    'description' => '中介公司',
    'tablename' => 'member_company',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '1',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '3',
    'type' => '2',
  ),
);
?>