<?php
return array (
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '1',
    'thumb' => '',
  ),
  57 => 
  array (
    'posid' => '57',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '2',
    'thumb' => '',
  ),
  58 => 
  array (
    'posid' => '58',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '90',
    'siteid' => '2',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '90',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '89',
    'siteid' => '1',
    'thumb' => '',
  ),
  59 => 
  array (
    'posid' => '59',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '89',
    'siteid' => '2',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条3',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '88',
    'siteid' => '1',
    'thumb' => '',
  ),
  60 => 
  array (
    'posid' => '60',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条3',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '88',
    'siteid' => '2',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条1_下5条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '87',
    'siteid' => '1',
    'thumb' => '',
  ),
  61 => 
  array (
    'posid' => '61',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条1_下5条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '87',
    'siteid' => '2',
    'thumb' => '',
  ),
  62 => 
  array (
    'posid' => '62',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条2_下4条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '86',
    'siteid' => '2',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条2_下4条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '86',
    'siteid' => '1',
    'thumb' => '',
  ),
  63 => 
  array (
    'posid' => '63',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页_头条3_下4条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '85',
    'siteid' => '2',
    'thumb' => '',
  ),
  39 => 
  array (
    'posid' => '39',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_头条3_下4条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '85',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页_推荐楼盘1（7图）',
    'maxnum' => '7',
    'extention' => '',
    'listorder' => '82',
    'siteid' => '1',
    'thumb' => '',
  ),
  55 => 
  array (
    'posid' => '55',
    'modelid' => '21',
    'catid' => '74',
    'name' => '首页_推荐楼盘1（7图）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '82',
    'siteid' => '2',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页_推荐楼盘2（7图）',
    'maxnum' => '21',
    'extention' => '',
    'listorder' => '81',
    'siteid' => '1',
    'thumb' => '',
  ),
  56 => 
  array (
    'posid' => '56',
    'modelid' => '21',
    'catid' => '74',
    'name' => '首页_推荐楼盘2（7图）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '81',
    'siteid' => '2',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页_精品楼盘1（2图）',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '80',
    'siteid' => '1',
    'thumb' => '',
  ),
  7 => 
  array (
    'posid' => '7',
    'modelid' => '5',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '80',
    'siteid' => '1',
    'thumb' => '',
  ),
  64 => 
  array (
    'posid' => '64',
    'modelid' => '21',
    'catid' => '0',
    'name' => '首页_精品楼盘1（2图）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '80',
    'siteid' => '2',
    'thumb' => '',
  ),
  79 => 
  array (
    'posid' => '79',
    'modelid' => '29',
    'catid' => '0',
    'name' => '首页_推荐楼盘1（7图）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '80',
    'siteid' => '3',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页_精品楼盘2（8条）',
    'maxnum' => '10',
    'extention' => '',
    'listorder' => '79',
    'siteid' => '1',
    'thumb' => '',
  ),
  65 => 
  array (
    'posid' => '65',
    'modelid' => '21',
    'catid' => '0',
    'name' => '首页_精品楼盘2（8条）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '79',
    'siteid' => '2',
    'thumb' => '',
  ),
  80 => 
  array (
    'posid' => '80',
    'modelid' => '29',
    'catid' => '0',
    'name' => '首页_推荐楼盘2（7图）',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '79',
    'siteid' => '3',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页_搜索框下推荐楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '77',
    'siteid' => '1',
    'thumb' => '',
  ),
  66 => 
  array (
    'posid' => '66',
    'modelid' => '21',
    'catid' => '0',
    'name' => '首页_搜索框下推荐楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '77',
    'siteid' => '2',
    'thumb' => '',
  ),
  81 => 
  array (
    'posid' => '81',
    'modelid' => '29',
    'catid' => '0',
    'name' => '首页_搜索框下推荐楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '75',
    'siteid' => '3',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '13',
    'catid' => '14',
    'name' => '新房首页_推荐楼盘',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '70',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '13',
    'catid' => '14',
    'name' => '新房首页_推荐户型',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '65',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '13',
    'catid' => '14',
    'name' => '新房首页_推荐样板间',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '64',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '46',
    'name' => '商业地产_首页焦点图',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '59',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '1',
    'catid' => '20',
    'name' => '旅游地产_首页焦点图',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '58',
    'siteid' => '1',
    'thumb' => '',
  ),
  75 => 
  array (
    'posid' => '75',
    'modelid' => '29',
    'catid' => '0',
    'name' => '新房首页推荐楼盘',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '58',
    'siteid' => '3',
    'thumb' => '',
  ),
  45 => 
  array (
    'posid' => '45',
    'modelid' => '21',
    'catid' => '74',
    'name' => '新房首页推荐楼盘',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '58',
    'siteid' => '2',
    'thumb' => '',
  ),
  48 => 
  array (
    'posid' => '48',
    'modelid' => '21',
    'catid' => '74',
    'name' => '首页_精品楼盘1（2图）',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '57',
    'siteid' => '2',
    'thumb' => '',
  ),
  49 => 
  array (
    'posid' => '49',
    'modelid' => '21',
    'catid' => '74',
    'name' => '首页_精品楼盘2（8条）',
    'maxnum' => '8',
    'extention' => '',
    'listorder' => '56',
    'siteid' => '2',
    'thumb' => '',
  ),
  46 => 
  array (
    'posid' => '46',
    'modelid' => '21',
    'catid' => '74',
    'name' => '新房首页推荐户型',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '55',
    'siteid' => '2',
    'thumb' => '',
  ),
  47 => 
  array (
    'posid' => '47',
    'modelid' => '21',
    'catid' => '74',
    'name' => '新房首页推荐样板间',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '54',
    'siteid' => '2',
    'thumb' => '',
  ),
  76 => 
  array (
    'posid' => '76',
    'modelid' => '29',
    'catid' => '0',
    'name' => '新房首页推荐户型',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '52',
    'siteid' => '3',
    'thumb' => '',
  ),
  77 => 
  array (
    'posid' => '77',
    'modelid' => '29',
    'catid' => '0',
    'name' => '新房首页推荐样板间',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '51',
    'siteid' => '3',
    'thumb' => '',
  ),
  78 => 
  array (
    'posid' => '78',
    'modelid' => '29',
    'catid' => '0',
    'name' => '推广楼盘',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '50',
    'siteid' => '3',
    'thumb' => '',
  ),
  67 => 
  array (
    'posid' => '67',
    'modelid' => '23',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '42',
    'siteid' => '2',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '40',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '13',
    'catid' => '0',
    'name' => '在售商业地产推荐',
    'maxnum' => '8',
    'extention' => '',
    'listorder' => '30',
    'siteid' => '1',
    'thumb' => '',
  ),
  69 => 
  array (
    'posid' => '69',
    'modelid' => '21',
    'catid' => '0',
    'name' => '在售商业地产推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '30',
    'siteid' => '2',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '13',
    'catid' => '0',
    'name' => '精品商业地产Ⅰ',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '28',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '13',
    'catid' => '0',
    'name' => '精品商业地产Ⅱ',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '26',
    'siteid' => '1',
    'thumb' => '',
  ),
  54 => 
  array (
    'posid' => '54',
    'modelid' => '23',
    'catid' => '0',
    'name' => '资讯_首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '25',
    'siteid' => '2',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '13',
    'catid' => '0',
    'name' => '在售旅游地产推荐',
    'maxnum' => '8',
    'extention' => '',
    'listorder' => '25',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '13',
    'catid' => '0',
    'name' => '精品旅游地产Ⅰ',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '24',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '13',
    'catid' => '0',
    'name' => '精品旅游地产Ⅱ',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '23',
    'siteid' => '1',
    'thumb' => '',
  ),
  71 => 
  array (
    'posid' => '71',
    'modelid' => '13',
    'catid' => '14',
    'name' => '新房楼盘超市页_推广楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '22',
    'siteid' => '1',
    'thumb' => '',
  ),
  43 => 
  array (
    'posid' => '43',
    'modelid' => '1',
    'catid' => '0',
    'name' => '看房团首页_优惠打折信息',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '22',
    'siteid' => '1',
    'thumb' => '',
  ),
  44 => 
  array (
    'posid' => '44',
    'modelid' => '13',
    'catid' => '0',
    'name' => '看房团首页_热点楼盘团购',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '21',
    'siteid' => '1',
    'thumb' => '',
  ),
  83 => 
  array (
    'posid' => '83',
    'modelid' => '13',
    'catid' => '0',
    'name' => '看房团-备选楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '21',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '1',
    'catid' => '0',
    'name' => '资讯_首页焦点图',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '20',
    'siteid' => '1',
    'thumb' => '',
  ),
  42 => 
  array (
    'posid' => '42',
    'modelid' => '1',
    'catid' => '0',
    'name' => '资讯_首页精品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '19',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '1',
    'catid' => '0',
    'name' => '资讯首页_图片新闻焦点图',
    'maxnum' => '5',
    'extention' => '',
    'listorder' => '18',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '1',
    'catid' => '0',
    'name' => '资讯_右侧图片推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '17',
    'siteid' => '1',
    'thumb' => '',
  ),
  50 => 
  array (
    'posid' => '50',
    'modelid' => '23',
    'catid' => '0',
    'name' => '内容_标题下 推荐1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '16',
    'siteid' => '2',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '1',
    'catid' => '0',
    'name' => '内容_标题下 推荐1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '16',
    'siteid' => '1',
    'thumb' => '',
  ),
  51 => 
  array (
    'posid' => '51',
    'modelid' => '23',
    'catid' => '0',
    'name' => '内容_标题下 推荐2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '15',
    'siteid' => '2',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '1',
    'catid' => '0',
    'name' => '内容_标题下 推荐2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '15',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '1',
    'catid' => '0',
    'name' => '内容_标题下 图1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '14',
    'siteid' => '1',
    'thumb' => '',
  ),
  52 => 
  array (
    'posid' => '52',
    'modelid' => '23',
    'catid' => '0',
    'name' => '内容_标题下 图1',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '14',
    'siteid' => '2',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '1',
    'catid' => '0',
    'name' => '内容_标题下 图2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '13',
    'siteid' => '1',
    'thumb' => '',
  ),
  53 => 
  array (
    'posid' => '53',
    'modelid' => '23',
    'catid' => '0',
    'name' => '内容_标题下 图2',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '13',
    'siteid' => '2',
    'thumb' => '',
  ),
  68 => 
  array (
    'posid' => '68',
    'modelid' => '4',
    'catid' => '0',
    'name' => '图库_首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '11',
    'siteid' => '1',
    'thumb' => '',
  ),
  40 => 
  array (
    'posid' => '40',
    'modelid' => '1',
    'catid' => '0',
    'name' => '右侧视频推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '1',
    'thumb' => '',
  ),
  70 => 
  array (
    'posid' => '70',
    'modelid' => '4',
    'catid' => '0',
    'name' => '图库内页_推荐组图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '1',
    'thumb' => '',
  ),
  74 => 
  array (
    'posid' => '74',
    'modelid' => '4',
    'catid' => '0',
    'name' => '图库_播放结束推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '82',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  11 => 
  array (
    'posid' => '11',
    'modelid' => '1',
    'catid' => '53',
    'name' => '家居首页_头条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '1',
    'catid' => '53',
    'name' => '家居首页_焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  41 => 
  array (
    'posid' => '41',
    'modelid' => '1',
    'catid' => '0',
    'name' => '[新1]大头条下3条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  84 => 
  array (
    'posid' => '84',
    'modelid' => '1',
    'catid' => '6',
    'name' => '二手房首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  72 => 
  array (
    'posid' => '72',
    'modelid' => '21',
    'catid' => '74',
    'name' => '新房_楼盘超市_推广楼盘',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  82 => 
  array (
    'posid' => '82',
    'modelid' => '1',
    'catid' => '6',
    'name' => '微信专栏',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  73 => 
  array (
    'posid' => '73',
    'modelid' => '23',
    'catid' => '0',
    'name' => '资讯_首页精品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '1',
    'catid' => '0',
    'name' => '[新1]大头条',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>