<?php
return array (
  8 => 
  array (
    'typeid' => '8',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '开发商',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '1',
    'description' => '',
  ),
  9 => 
  array (
    'typeid' => '9',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '投资商',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '2',
    'description' => '',
  ),
  10 => 
  array (
    'typeid' => '10',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '代理公司',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '3',
    'description' => '',
  ),
  11 => 
  array (
    'typeid' => '11',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '物业公司',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '4',
    'description' => '',
  ),
  12 => 
  array (
    'typeid' => '12',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '实景图',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '5',
    'description' => '',
  ),
  13 => 
  array (
    'typeid' => '13',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '效果图',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '6',
    'description' => '',
  ),
  14 => 
  array (
    'typeid' => '14',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '交通图',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '7',
    'description' => '',
  ),
  15 => 
  array (
    'typeid' => '15',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '配套图',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '8',
    'description' => '',
  ),
  16 => 
  array (
    'typeid' => '16',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '样板间',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '9',
    'description' => '',
  ),
  17 => 
  array (
    'typeid' => '17',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '活动图',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '10',
    'description' => '',
  ),
  18 => 
  array (
    'typeid' => '18',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '一室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '11',
    'description' => '',
  ),
  19 => 
  array (
    'typeid' => '19',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '两室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '12',
    'description' => '',
  ),
  20 => 
  array (
    'typeid' => '20',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '三室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '13',
    'description' => '',
  ),
  21 => 
  array (
    'typeid' => '21',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '四室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '14',
    'description' => '',
  ),
  22 => 
  array (
    'typeid' => '22',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '五室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '15',
    'description' => '',
  ),
  23 => 
  array (
    'typeid' => '23',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '六室',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '16',
    'description' => '',
  ),
  24 => 
  array (
    'typeid' => '24',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '复式',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '17',
    'description' => '',
  ),
);
?>