<?php
return array (
  1 => '{$categorydir}{$catdir}/index.html|{$categorydir}{$catdir}/{$page}.html',
  6 => 'index.php?s=content/index/lists/catid/{$catid}|index.php?s=content/index/lists/catid/{$catid}/page/{$page}',
  11 => '{$categorydir}{$year}/{$catdir}_{$month}{$day}/{$id}.html|{$categorydir}{$year}/{$catdir}_{$month}{$day}/{$id}_{$page}.html',
  12 => '{$categorydir}{$catdir}/{$year}/{$month}{$day}/{$id}.html|{$categorydir}{$catdir}/{$year}/{$month}{$day}/{$id}_{$page}.html',
  16 => 'index.php?s=content/index/show/catid/{$catid}/id/{$id}|index.php?s=content/index/show/catid/{$catid}/id/{$id}/page/{$page}',
  17 => 'show-{$catid}-{$id}-{$page}.html',
  18 => 'content-{$catid}-{$id}-{$page}.html',
  30 => 'list{$lst}-g{$page}.html',
  31 => 'wenfang{$lst}-p{$page}.html',
  32 => 'list-{$page}.html',
  33 => '{$house_path}{$id}',
  34 => '{$house_path}company-{$id}.html',
  35 => '{$house_path}{$relation}/huxing.html',
  36 => '{$house_path}{$relation}/dongtai.html',
  37 => '{$house_path}{$relation}/xiangce.html',
  38 => '{$house_path}{$relation}/jiage.html',
  40 => 'piclist-{$page}.html',
  41 => '{$house_path}{$xglp}/wenfang-p1.html',
  42 => 'ybjlist{$lst}-p{$page}.html',
  43 => 'hxlist{$lst}-p{$page}.html',
  44 => '{$house_path}{$relation}/dianping.html',
  45 => 'xclist{$lst}-p{$page}.html',
  46 => '{$house_path}fangyuan/{$id}.html',
  47 => '{$tuan_path}route_{$id}.html',
  48 => 'rent-list{$lst}-g{$page}.html',
  49 => 'xiaoqu-list{$lst}-g{$page}.html',
  13 => '{$esf_path}show-{$id}.html',
  14 => '{$esf_path}rent-show-{$id}.html',
  15 => '{$esf_path}xiaoqu-show-{$id}.html',
);
?>